package com.tata.spring.ws.proxies;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-01-17T19:47:43.304+05:30
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "EmployeeDetailsServices", 
                  wsdlLocation = "file:/C:/Users/oletit/AppData/Local/Temp/tempdir5033384426786836756.tmp/empdetails_1.wsdl",
                  targetNamespace = "http://com.tata.hpe") 
public class EmployeeDetailsServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com.tata.hpe", "EmployeeDetailsServices");
    public final static QName EmployeeDetailsServiceSoap11 = new QName("http://com.tata.hpe", "EmployeeDetailsServiceSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/oletit/AppData/Local/Temp/tempdir5033384426786836756.tmp/empdetails_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeDetailsServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/oletit/AppData/Local/Temp/tempdir5033384426786836756.tmp/empdetails_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeDetailsServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeDetailsServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeDetailsServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EmployeeDetailsServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EmployeeDetailsServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EmployeeDetailsServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EmployeeDetailsService
     */
    @WebEndpoint(name = "EmployeeDetailsServiceSoap11")
    public EmployeeDetailsService getEmployeeDetailsServiceSoap11() {
        return super.getPort(EmployeeDetailsServiceSoap11, EmployeeDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeDetailsService
     */
    @WebEndpoint(name = "EmployeeDetailsServiceSoap11")
    public EmployeeDetailsService getEmployeeDetailsServiceSoap11(WebServiceFeature... features) {
        return super.getPort(EmployeeDetailsServiceSoap11, EmployeeDetailsService.class, features);
    }

}
